version: '3.9'

services:
  api_back_personal_control:
    container_name: api_back_personal_control
    build: .
    command: sh -c 'npx prisma migrate deploy & npm run start:dev'
    depends_on:
      - postgres_back_personal_control
    networks:
      - network_back_personal_control
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - .:/home/api/node/back_personal_control

  postgres_back_personal_control:
    container_name: postgres_back_personal_control
    image: postgres:16.3-alpine
    networks:
      - network_back_personal_control
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data_back_personal_control:/var/lib/postgresql/data

networks:
  network_back_personal_control:


volumes:
  postgres_data_back_personal_control:
